name: Run operations on a deb repo (from an Ubuntu system)

on:
  push:
    branches: [ dev ]
  pull_request:
    push:
      branches: [ stable ]
jobs:
  run-operations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Install PHP modules
        # run: sudo apt-get install -y php-cli php7.4-json php7.4-sqlite3 sqlite3
        run: sudo apt-get install -y php-cli php8.1-sqlite3 sqlite3

      - name: Print PHP version
        run: php --version

      - name: Install dependencies packages
        # run: sudo apt-get install -y debmirror reprepro curl gnupg2 yum-utils createrepo
        run: sudo apt-get install -y debmirror reprepro curl gnupg2

      - name: Set up repomanager files & directories
        run: |
          sudo groupadd repomanager
          sudo usermod -a -G repomanager www-data
          sudo mkdir -p /home/repo
          sudo mkdir -p /etc/yum.repos.d/repomanager
          sudo mkdir -p /var/www/repomanager
          sudo mkdir -p /var/www/repomanager/backups
          sudo mkdir -p /var/www/repomanager/logs/main
          sudo mkdir -p /var/www/repomanager/cron
          sudo mkdir -p /var/www/repomanager/configurations
          sudo mkdir -p /var/www/repomanager/operations/pool/
          sudo mkdir -p /var/www/repomanager/db
          sudo mkdir -p /var/www/repomanager/.gnupg
          sudo cp -r $GITHUB_WORKSPACE/www/* /var/www/repomanager/
          sudo cp $GITHUB_WORKSPACE/version /var/www/repomanager/
          sudo cp $GITHUB_WORKSPACE/www/repomanager /var/www/repomanager/

      - name: Set up repomanager main config
        run: |
          sudo curl -s -o /var/www/repomanager/configurations/repomanager.conf https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/repomanager.conf 2> /dev/null
          sudo curl -s -L -o /var/www/repomanager/db/repomanager.db https://github.com/lbr38/resources/raw/main/ci/repomanager/repomanager.db 2> /dev/null
          sudo ls -l /var/www/repomanager/configurations/
          sudo ls -l /var/www/repomanager/db/
      
      - name: Generate repomanager GPG signing key
        run: |
          echo "Key-Type: RSA" > /tmp/gpg-template-file
          echo "Key-Length: 2048" >> /tmp/gpg-template-file
          echo "Key-Usage: sign" >> /tmp/gpg-template-file
          echo "Name-Real: Repomanager" >> /tmp/gpg-template-file
          echo "Name-Comment: No description" >> /tmp/gpg-template-file
          echo "Name-Email: gpgkey@nomail.com" >> /tmp/gpg-template-file
          echo "Expire-Date: 0" >> /tmp/gpg-template-file
          echo "Passphrase: beautifulPassphrase" >> /tmp/gpg-template-file
          sudo gpg2 --batch --gen-key --homedir /var/www/repomanager/.gnupg/ --no-permission-warning /tmp/gpg-template-file 2>/dev/null
          echo "beautifulPassphrase" > passphrase
          sudo mv passphrase /var/www/repomanager/.gnupg/passphrase
          rm /tmp/gpg-template-file

      - name: Set up GPG config
        run: |
          echo -e "pinentry-mode loopback\npassphrase-file /var/www/repomanager/.gnupg/passphrase" > gpg.conf 
          sudo mv gpg.conf /var/www/repomanager/.gnupg/gpg.conf

      - name: Download jobs
        run: |
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-mirror-repo.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-mirror-repo.json 2> /dev/null
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-update-repo.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-update-repo.json 2> /dev/null
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-duplicate-repo.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-duplicate-repo.json 2> /dev/null
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-create-env.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-create-env.json 2> /dev/null
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-delete.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-delete.json 2> /dev/null
          sudo curl -s -o /var/www/repomanager/operations/pool/ci-reconstruct.json https://raw.githubusercontent.com/lbr38/resources/main/ci/repomanager/operations/deb/ci-reconstruct.json 2> /dev/null

      - name: Set up permissions
        run: sudo /var/www/repomanager/repomanager -p

      - name: Run job - Mirror repo
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-mirror-repo'

      - name: Print mirrored repo content
        run: sudo ls -l /home/repo/debian/buster/contrib_pprd/pool/contrib/

      - name: Run job - Update repo
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-update-repo'

      - name: Run job - Duplicate repo
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-duplicate-repo'

      - name: Print duplicated repo content
        run: sudo ls -l /home/repo/debian-copy/buster/contrib_pprd/pool/contrib/

      - name: Run job - Create repo env
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-create-env'

      - name: Run job - Reconstruct repo
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-reconstruct'

      - name: Run job - Delete repo
        run: sudo -u www-data php /var/www/repomanager/operations/execute.php --id='ci-delete'